# Generated by Django 5.1.6 on 2025-02-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('start_shift', models.TimeField(null=True)),
                ('end_shift', models.TimeField(null=True)),
                ('tags', models.ManyToManyField(related_name='barbearias', to='api.tag')),
            ],
        ),
    ]
